#ifndef FEDER_DATAFEED_LOG_HH
#define FEDER_DATAFEED_LOG_HH

#include "soil/Log.hh"

#define DATAFEED_LOG_INIT(x) SOIL_LOG_INIT(x)

#define DATAFEED_TRACE SOIL_TRACE
#define DATAFEED_DEBUG SOIL_DEBUG
#define DATAFEED_INFO  SOIL_INFO
#define DATAFEED_WARNING SOIL_WARNING
#define DATAFEED_ERROR SOIL_ERROR
#define DATAFEED_FATAL SOIL_FATAL
#define DATAFEED_PDU SOIL_PDU


#endif
