#ifndef FEDER__LOG_HH
#define FEDER_LOG_HH

#include "soil/Log.hh"

#define FEDER_LOG_INIT(x) SOIL_LOG_INIT(x)

#define FEDER_TRACE SOIL_TRACE
#define FEDER_DEBUG SOIL_DEBUG
#define FEDER_INFO  SOIL_INFO
#define FEDER_WARNING SOIL_WARNING
#define FEDER_ERROR SOIL_ERROR
#define FEDER_FATAL SOIL_FATAL
#define FEDER_PDU SOIL_PDU


#endif
